name: "⚙ Backend 작업"
description: "백엔드 작업 생성"
labels: ["team: Backend"]
body:
  - type: textarea
    id: description
    attributes:
      label: 작업 내용
      placeholder: "작업 내용을 상세히 적어주세요"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      options:
        - 높음
        - 중간
        - 낮음
    validations:
      required: true